# -*- coding: utf-8 -*-
"""Machinelearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QlvShehkYQoD0y8qcSFcfg_fUewi47Sf
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

df= pd.read_csv("House_Rent_Dataset.csv")

df.head()

df.shape

# y is the rent column if the data frame
y = df['Rent']

df.info()
# objects are strings
# int are numbers

X = df[['BHK','Size','Bathroom']]

# Split the data into training and testing
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size= 0.2, random_state= 42)











